### ISSUE TITLE
Error arguments imply differing number of rows when using by_split()

### ISSUE THREAD

**Issue by lmob499** [tpronk/splithalfr#24]
Hi there,

I have been calculating reliability for a couple of cognitive bias tasks and this has been going well. However, I keep on getting the same error for one dataset which I cannot seem to solve. I am using a workaround for the fn_score function in which I return the score that already was calculated. This has worked perfectly fine for other tasks. I have tried the by_split() command with and without ncores=1. I have read about everything I could find, but cannot seem to fix this. Thanks so much for thinking along!

Code:
gng <- read.spss('GNG_pre.sav', to.data.frame=TRUE) 

fn_score <- function (gng){
  return (gng$new) 
  }

split_scores7 <- by_split(
  gng,
  gng$userid,
  fn_score,
  replications = 1000,
  careful=FALSE,
  ncores=1
)

I get either of these error messages when running this code:
Error in data.frame(participant = participant_ids[i], score_1 = fn_score(bind_rows(splitted_sets[[1]])),  : 
  arguments imply differing number of rows: 1, 0

Error in checkForRemoteErrors(val) : 
  4 nodes produced errors; first error: A stratum had less than two elements, so splitting it may give unexpected results, this error can be disabled by setting careful = FALSE

sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: aarch64-apple-darwin20
Running under: macOS Sonoma 14.4.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Amsterdam
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.1.4      foreign_0.8-86   splithalfr_2.2.2

loaded via a namespace (and not attached):
 [1] bridgesampling_1.1-2 tensorA_0.36.2.1     utf8_1.2.4           generics_0.1.3      
 [5] bcaboot_0.2-3        stringi_1.8.4        lattice_0.22-6       digest_0.6.37       
 [9] magrittr_2.0.3       evaluate_0.24.0      grid_4.4.1           timechange_0.3.0    
[13] fastmap_1.2.0        mvtnorm_1.2-6        Matrix_1.7-0         pkgbuild_1.4.4      
[17] ggthemes_5.1.0       backports_1.5.0      gridExtra_2.3        Brobdingnag_1.2-9   
[21] purrr_1.0.2          fansi_1.0.6          brms_2.21.0          QuickJSR_1.3.1      
[25] scales_1.3.0         codetools_0.2-20     mnormt_2.1.1         abind_1.4-5         
[29] cli_3.6.3            rlang_1.1.4          munsell_0.5.1        remotes_2.5.0       
[33] yaml_2.3.10          StanHeaders_2.32.10  tools_4.4.1          rstan_2.32.6        
[37] inline_0.3.19        parallel_4.4.1       rstantools_2.4.0     checkmate_2.3.2     
[41] coda_0.19-4.1        colorspace_2.1-1     ggplot2_3.5.1        vctrs_0.6.5         
[45] posterior_1.6.0      R6_2.5.1             matrixStats_1.3.0    stats4_4.4.1        
[49] lifecycle_1.0.4      lubridate_1.9.3      stringr_1.5.1        psych_2.4.6.26      
[53] pkgconfig_2.0.3      RcppParallel_5.1.9   pillar_1.9.0         gtable_0.3.5        
[57] loo_2.8.0            glue_1.7.0           Rcpp_1.0.13          xfun_0.47           
[61] tibble_3.2.1         tidyselect_1.2.1     knitr_1.48           rstudioapi_0.16.0   
[65] bayesplot_1.11.1     htmltools_0.5.8.1    nlme_3.1-164         rmarkdown_2.28      
[69] compiler_4.4.1       distributional_0.4.0

**Comment by tpronk** [comment]
Hey @lmob499, thanks for your question! My guess is that the dataframe (gng) received by fn_score has less rows than expected. Could you try printing it to the console? NB, this only works when ncores = 1

**Comment by lmob499** [comment]
Thanks for your quick response @tpronk ! Do you mean printing the dataset to the console? 
When doing so it gives me the expected number of rows:

    userid    new
1   138432   89.5
2   138438   60.5
3   138439   30.0
4   138440    7.5
5   138443   -5.0
6   138472    4.0
7   138476   15.0
8   138494  -39.5
9   138500   48.5
10  138502   -7.0
11  138503  -27.0
12  138513  -28.0
13  138521   38.0
14  138527  -79.5
15  138531  -45.0
16  138532   37.0
17  138550   15.0
18  138551   33.0
19  138554  -25.0
20  138557   31.0
21  138562   -8.5
22  138564  113.0
23  138574  -14.5
24  138576  114.0
25  138581    9.0
26  138592    0.5
27  138594    4.5
28  138599  -64.0
29  138624    2.5
30  138666   69.5
31  138674   31.0
32  138681   -0.5
33  138690    4.0
34  138695   23.5
35  138697   23.5
36  138704  -10.5
37  138719   27.5
38  138720  -16.0
39  138927    2.5
40  138936  127.5
41  139545  -13.5
42  139553  -12.5
43  139578   31.5
44  139990  -54.0
45  140527  -57.5
46  140559   27.0
47  140608  -44.5
48  140614  -12.0
49  140794  -13.0
50  140941   17.5
51  141418   50.0
52  141422   55.0
53  144879   13.0
54  144884  -18.5
55  144918   34.0
56  146749  -23.0
57  146759   15.0
58  147069  -61.5
59  147112  -17.0
60  147123  -32.0
61  147131  -27.0
62  147147   -3.0
63  147152   13.5
64  147154   -3.5
65  147156   47.0
66  147157  -89.5
67  147164  -37.5
68  147169   37.5
69  147174  -15.0
70  147175    8.0
71  147181   33.5
72  147182   60.0
73  147189   41.0
74  147193   60.0
75  147195  -58.5
76  147201  -26.5
77  147214  -66.5
78  147218  -19.0
79  147223   86.0
80  147228  -80.0
81  147232   56.5
82  147233    0.5
83  147234   18.0
84  147241  -69.0
85  147242   30.5
86  147246   44.0
87  147251   60.0
88  147253   39.0
89  147254   28.5
90  147268   23.0
91  147269  -11.5
92  147276   31.0
93  147281   27.5
94  147285   -2.5
95  147287  -47.0
96  147290  -31.5
97  147291    0.0
98  147295    7.5
99  147298  -72.0
100 147304   -8.0
101 151633   61.0
102 151636  132.5
103 151640   16.0
104 151641  -47.5
105 151650   73.0
106 151652  -33.5
107 153022   84.5
108 153025  -11.5
109 153040   35.0
110 153041   23.0
111 153043  -36.0
112 153047  -45.0
113 153054  -23.0
114 153710 -122.5
115 153717   26.0
116 153719   33.5
117 153720  -45.0
118 153721    4.5
119 153731   54.0
120 153732  -46.0
121 153733   11.5
122 153734 -150.0
123 153736  -54.5
124 153737  -50.0
125 153744  -14.5
126 153747  -17.5
127 153751   60.5
128 153754 -124.0
129 153759   -3.5
130 153780  113.0
131 153781  -62.5
132 153786   23.5
133 153821   39.0
134 153826    4.0
135 153829  -40.5
136 153846  -24.5
137 153860    6.5
138 153863   35.0
139 153865   11.0
140 153869   55.0
141 153871  -33.5
142 153873   -6.0
143 153874  196.5
144 153875  -29.0
145 153876  -20.0
146 153880   50.5
147 153881   60.5
148 153884  -29.0
149 153889   20.0
150 153901  -41.5
151 153906    9.5
152 153907    4.0
153 153914  -98.0
154 153916   34.0
155 153919  -51.0
156 153922    0.0
157 153928  -54.0
158 153933   31.0
159 153935   33.0
160 153936  -41.0
161 153938    2.0
162 153942   35.0
163 153947  -67.0
164 153949   20.5
165 153950  -56.0
166 153951   19.5
167 153953   18.5
168 153954  -24.5
169 153955  -14.5
170 153957   -1.5
171 153962   15.5
172 153964  -73.5
173 154179   17.0
174 154185   33.5
175 154196  -15.5
176 154197   90.0
177 154199  -54.5
178 156213   31.0
179 156214  -17.5
180 156218  100.5
181 156221   31.0
182 156250   35.5
183 156253  -15.0
184 156254   62.5
185 156266  116.0
186 156274   -0.5
187 156290  -10.0
188 156292   39.0
189 156293   -7.5
190 156302   35.5
191 156307  -40.0
192 156312  -57.0
193 156346   32.0
194 158191   25.0
195 158204   63.0
196 158407   14.0
197 158465   22.0
198 158698   69.0
199 158846    2.5
200 159052    6.5
201 159062  -13.0
202 159063   31.0
203 159064  -43.5
204 159286   -1.5
205 159287    1.5
206 159294  -93.0
207 159295   -8.0
208 159299  -15.5
209 159305  -49.0
210 159310 -108.0
211 159312   -0.5
212 159313  -56.0
213 159315   31.5
214 159323   -0.5
215 159325   44.5
216 159327   93.5
217 159334  -10.5
218 159335  -33.5
219 159339   50.5
220 159343  -18.0
221 159652  -75.0
222 159654   -8.5
223 159755  -10.0
224 159756   55.0
225 159758  136.5
226 159764  -52.0
227 159772   -7.5
228 159779   10.0
229 159781  -18.5
230 159784   64.5
231 159793  -15.5
232 159794  -93.5
233 159800  -33.5
234 159807  102.0
235 159813  -10.0

**Comment by tpronk** [comment]
Hey again, sorry for being a bit slow in replying this time; my last message was actually when I was on vacation :)

I actually had in mind something like printing the data received by `fn_score`, for instance like below...
```R
fn_score <- function (gng){
  print(gng)
  return (gng$new)
}
```

Regardless, based on what you reported, I think I know what's the problem. Splithalfr will try to calculate split-half reliabilities for each individual participant. In your case, it tries to do so for each unique value of userid. However, since there is only one row of data for each userid. it can't split anything.

**Comment by tpronk** [comment]
It was indeed, thnx! :)

If you only got one score per participant, you can't estimate split-half reliabilities; you need, for instance, trial-level data for that. See the Go/Nogo vignette for an example. You can open this vignette by loading the splithalfr package, and then run the statement below

`vignette("gng_dprime")`

**Comment by tpronk** [comment]
As far as I can tell, your implementation of the d-prime looks correct. In the splithalfr vignette, I simply pick the d-prime to illustrate the splithalfr with a relatively sophisticated scoring algorithm that sometimes has been used for Go-Nogo tasks, so I don't really have an opinion about what scoring algorithm would be most suitable. However, it's quite an interesting result that you found that different scoring algorithms yield such different reliabilities! It makes me think of [Glashouwer et al., 2013](https://doi.org/10.1016/j.jbtep.2012.07.015), who compared a whole bunch of algorithms for the IAT.

NB. As your follow-up question doesn't cover any issues with the splithalfr package, I'll mark this issue as closed, but feel free to discuss further on the [discussion board](https://github.com/tpronk/splithalfr/discussions).

**Comment by lmob499** [comment]
Thanks a lot!
